#!/usr/bin/env ruby

Autotest.add_hook :initialize do |at|
  %w{.svn .hg .git vendor solr}.each {|exception| 
    at.add_exception(exception)
  }
end

module Autotest::Growl
  def self.growl title, msg, img, pri=0, sticky=""
    system "growlnotify -n autotest --image #{img} -p #{pri} -m #{msg.inspect} #{title} #{sticky}"
  end

  Autotest.add_hook :ran_command do |at|
    # Example output: 324 examples, 2 failures, 13 pending
    output = at.results.last.slice(/(\d+)\s.*examples?,\s(\d+)\s.*failures?/)
    
    if output =~ /[1-9]\sfailures?/
      growl "Test Results", "#{output}", "~/dotfiles/autotest/images/fail.png", 2, "-s"
    else
      growl "Test Results", "#{output}", "~/dotfiles/autotest/images/pass.png"
    end
  end
end

