if has("gui_running")
  set guioptions=egmrt
  set guioptions-=r 

  set guifont=Monaco:h18
  set visualbell

  set columns=180

  if !hasmapto('<Plug>PeepOpen')
    map <unique> <silent> <leader>t <Plug>PeepOpen
  endif
endif

