call pathogen#infect()

syntax on
colorscheme Tomorrow
filetype indent plugin on

" Windows
" ============================================================================
set splitbelow splitright
set equalalways
set winminheight=0
set winminwidth=0

set spelllang=en_us

let mapleader = ","
let maplocalleader = ","

:noremap <leader>v :vsp<CR>:enew<CR>:pwd<CR>
:noremap <leader>s :split<CR>:enew<CR>:pwd<CR>
:noremap <leader>l <C-w>l
:noremap <leader>h <C-w>h
:noremap <leader>j <C-w>j
:noremap <leader>k <C-w>k
:noremap <leader>- <C-W>_                       
:noremap <leader>N <C-W>n<C-W>_
:noremap <leader>? <C-W>n<C-W>H<C-W>q
:noremap <leader>c :only<CR>:tabonly<CR>
:noremap J <Esc><C-w>j<C-w>_
:noremap K <Esc><C-w>k<C-w>_
:noremap <leader>r :! cutest %<CR>
:noremap <leader>/ <C-W>n<C-W>H<C-W>q<C-W>t<C-W>_<C-W>l<C-W>_<C-W>l<C-W>_<C-W>l<C-W>_
:noremap <leader>n :NERDTreeToggle<CR>

:noremap <leader>f :FufFile<CR>
:noremap <leader>b :FufBuffer<CR>

:noremap <leader>gst :!tig status<CR>
:noremap <leader>gpr :!git pull --rebase<CR>
:noremap <leader>gup :!git pull<CR>
:noremap <leader>gush :!git push<CR>

" Tabs
" ============================================================================
set expandtab
set softtabstop=2
set shiftwidth=2
set tabstop=2
set smarttab
set autoindent
set textwidth=0
set showtabline=2
set laststatus=1

" Searching
" ============================================================================
set hlsearch   " highlight search
set incsearch  " incremental search, search as you type
set ignorecase " Ignore case when searching 
set smartcase  " Ignore case when searching lowercase

" Directories
" ============================================================================
" Setup backup location and enable
set backupdir=~/.backup/vim
set backup

" Set Swap directory
set directory=~/.backup/vim/swap

" Change file completion to mimic shell behavior
set wildmenu
set wildmode=list:longest
set wildignore+=*/tmp/*,*/.gs/*,*.DS_Store,*.rdb,*.aof,*.sqlite3,*.pid

" Inser New Line
" ============================================================================
:noremap <S-Enter> O<ESC> 
:noremap <Enter> o<ESC>

" Set encodings to UTF8
" ============================================================================
set encoding=utf-8
set fileencoding=utf-8

set list listchars=tab:>-,trail:.,extends:>

" Allow backspace to work on auto indents, EOL, or start of lines.
set backspace=indent,eol,start

" Change mapping of CtrlP
let g:ctrlp_map = '<leader>t'
