call pathogen#infect()

syntax on
filetype indent plugin on

" Highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Windows
" ============================================================================
set splitbelow splitright
set equalalways
set winminheight=0
set winminwidth=0

set spelllang=en_us

let mapleader = ","
let maplocalleader = ","

inoremap jk <ESC>
:noremap <leader>v :vsp<CR>:enew<CR>:pwd<CR>
:noremap <leader>s :split<CR>:enew<CR>:pwd<CR>
:noremap <leader>l <C-w>l
:noremap <leader>h <C-w>h
:noremap <leader>j <C-w>j
:noremap <leader>k <C-w>k
:noremap <leader>- <C-W>_
:noremap <leader>N <C-W>n<C-W>_
:noremap <leader>? <C-W>n<C-W>H<C-W>q
:noremap <leader>c :only<CR>:tabonly<CR>
:noremap <leader>/ <C-W>n<C-W>H<C-W>q<C-W>t<C-W>_<C-W>l<C-W>_<C-W>l<C-W>_<C-W>l<C-W>_
:noremap <leader>n :NERDTreeToggle<CR>
:noremap <leader>b :CtrlPBuffer<CR>

:noremap <leader>gb :GoBuild<CR>
:noremap <leader>gr :GoRun<CR>
:noremap <leader>gl :GoLint<CR>
:noremap <leader>gm :GoMetaLinter<CR>
:noremap <leader>gt :GoTest<CR>

" Tabs
" ============================================================================
set textwidth=0
set showtabline=2
set laststatus=1

" Searching
" ============================================================================
set nohlsearch " highlight search
set incsearch  " incremental search, search as you type
set ignorecase " Ignore case when searching
set smartcase  " Ignore case when searching lowercase

" Directories
" ============================================================================
" Setup backup location and enable
set backupdir=~/.backup/vim
set backup

" Set Swap directory
set directory=~/.backup/vim/swap

" Change file completion to mimic shell behavior
set wildmenu
set wildmode=list:longest
set wildignore+=*/tmp/*,*/.gs/*,*.DS_Store,*.rdb,*.aof,*.sqlite3,*.pid

" Set encodings to UTF8
" ============================================================================
set encoding=utf-8
set fileencoding=utf-8

" Allow backspace to work on auto indents, EOL, or start of lines.
set backspace=indent,eol,start

" Change mapping of CtrlP
let g:ctrlp_map = '<leader>t'
let g:ctrlp_custom_ignore = '\v[\/](\.git|node_modules)$'

" Change go defaults; save will do :GoImports
let g:go_fmt_command = "goimports"
