#! /bin/bash

# App specific secrets
if [ -e ~/.dg_secret ]; then source ~/.dg_secret; fi
if [ -e ~/.openredis_secret ]; then source ~/.openredis_secret; fi

# Amazon S3 Configuration
if [[ -f ~/.amazon_keys ]]; then source ~/.amazon_keys; fi

# Authorize.NET development settings
if [[ -f ~/.authorize-net ]]; then source ~/.authorize-net; fi

# Enable rbenv shims and autocompletion
eval "$(rbenv init -)"
