#! /bin/bash

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

# Bash prompt:
# 1. It has the current GIT_AUTHOR_EMAIL
# 2. The current git branch
# 3. The current folder
# 4. The current ruby + gemset combination i.e. `1.9.2@ohm`.
PS1="\$GIT_AUTHOR_EMAIL\[\033[0;35m\]\w\[\033[0;36m\]"
PS1="$PS1 \$(parse_git_branch)\[\033[00m\]\n\033[0;36m→\033[1;37m "
PS1="\033[0;33m\$(~/.rvm/bin/rvm-prompt v g | grep -v "ruby-") $PS1"
export PS1

# RVM
if [[ -s ~/.rvm/scripts/rvm ]] ; then source ~/.rvm/scripts/rvm ; fi

# Amazon S3 Configuration
if [[ -f ~/.amazon_keys ]]; then source ~/.amazon_keys; fi