#!/bin/bash
alias e="mvim"

pg() {
  if [ $1 == "start" ]
  then
    pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
  else
    pg_ctl -D /usr/local/var/postgres stop -s -m fast
  fi
}

ssh-tunnel() {
  ssh DG-SANDBOX -R :8888:127.0.0.1:9393 sleep 99999
}

global() {
  cd $GEM_HOME/../ruby-1.9.2-p0\@global/gems/$@* && vi
}

# Kudos to djanowski for this. Use ack to search files and open it in
# `vi` with the searched text as the last searched phrase in vi.
vack() {
  vi -p -c "/$1" $(ack -al $@)
}

# Search all files by default. This fixes the problem that *.css, *.less,
# *.sass files aren't usually seacrched.
alias ack="ack -a"

# Display this file, with basic highlighting.
alias ah="cat ~/dotfiles/bash/aliases/common | \
          highlight \
            blue '^# .*' \
            cyan '^alias' \
            purple '".*"' \
            red ' .*=' \
            yellow '=' | less -R"

# Utility
alias reload="source ~/.bashrc"

# Edit aliases.
alias ea="mvim -f ~/dotfiles/bash/aliases/common && reload"

# Edit environment vars.
alias ee="mvim -f ~/dotfiles/bash/env && reload"

# Common commands.
alias a="ls -A"           # -A all except literal . ..
alias la="ls -A -l -G"
alias c="clear"
alias cdd="cd -"          # goto last dir cd"ed from
alias cl="clear; l"
alias cls="clear; ls"
alias h="history"
alias l.="ls -d .[^.]*"
alias l="ls -lhGt"        # -l long listing, most recent first
                          # -G color
alias lh="ls -lh"
alias ll="ls -lhG"        # -l long listing, human readable, no group info
alias lt="ls -lt"         # sort with recently modified first
alias md="mkdir -p"
alias ..="cd .."          # up one dir